go:
  targets:
    - index.xml
    - skin.html
    - style.css
  out_dir: production

var:
  defaultColor:
    backCol:       '#FFFFFF'
    baseTextCol:   '#666666'
    listBack:      '#F4F4F4'
    borderCol:     '#DDDDDD'
    frameBack:     '#111144'
    frameFore:     '#FFFFFF'
    pointCol:      '#FF6644'
    bonmunTextCol: '#000000'
    bonmunForm:    '#CCBBAA'
    bonmunActing:  '#66AA00'
    highlight:     '#F0FF40'

  font: # REFERENCES fonts
    base: sans
    userName: serif
    title: serif
    sticker: thick
    deco: handwriting
    bonmun_base: serif
    bonmun_littleTitle: sans
    bonmun_deco: thick
    code: monospace

skin:
  liststyle:
    options:
      train:
        label: '큼직 한 줄'
      album:
        label: '썸네일만'
      card:
        label: '썸네일 및 제목'
      postit:
        label: '작은 메모'
      detailed:
        label: '복잡 목록'
    default_base: postit
    default:
      # 화면별 기본 스타일
#     index:             # 홈
#     category:          # 카테고리
#     archive:           # 보관함
      tag:      postit   # 태그
      search:   detailed # 검색결과
#     location:          # 지역로그

  homecover:
    menubar:
      label: '메뉴바'
      desc: '블로그 메뉴 및 검색창. 블로그 메뉴 이후 아래 "입력한 글 목록"에 정의된 항목이 나온다. 화면에는 타이틀만 표시되고 내용, 이미지는 안 보인다.'
    train:
      label: '큼직 한 줄'
      desc: '글목록 옵션의 큼직 한 줄과 같다.'
    card:
      label: '작은 앨범'
      desc: '썸네일 오른쪽왼쪽 번갈아 붙임.'
    bookcover:
      label: '책표지'
      desc: '썸네일로 왕큰 배경 함.'
    widepage:
      label: '책장'
      desc: '책장처럼 넘겨본다.'
# XXX 이원화됨. 애초에 이것들이 소스랑 분리돼 settings에 있을 이유가 있을가?

fonts:
  sans:
    url: 'https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100..900&display=swap'
    cssValue: "'Noto Sans KR', sans-serif"
  serif:
    url: 'https://fonts.googleapis.com/css2?family=Noto+Serif+KR&display=swap'
    cssValue: "'Noto Serif KR', serif"
  monospace:
    url: 'https://cdn.jsdelivr.net/gh/wan2land/d2coding/d2coding-full.css'
    cssValue: "'D2Coding', consolas, monospace"
  handwriting:
    url: 'https://fonts.googleapis.com/css2?family=Gaegu&display=swap'
    cssValue: "'Gaegu', cursive"
  thick:
    url: 'https://fonts.googleapis.com/css2?family=Jua&display=swap'
    cssValue: "'Jua', sans-serif"

meta:
  skinname: 'Text-Note-Book'
